package main

import "testing"

func Test_convertKanaToRomaji(t *testing.T) {
	type args struct {
		ks string
	}
	tests := []struct {
		name    string
		args    args
		wantRs  string
		wantErr bool
	}{
		{name: "かっこいい", args: args{ks: "かっこいい"}, wantRs: "kakkoii", wantErr: false},
		{name: "がっこう", args: args{ks: "がっこう"}, wantRs: "gakko", wantErr: false},
		{name: "ぴったり", args: args{ks: "ぴったり"}, wantRs: "pittari", wantErr: false},
		{name: "ふぁんたじー", args: args{ks: "ふぁんたじー"}, wantRs: "fuantaji", wantErr: false},
		{name: "びっくり", args: args{ks: "びっくり"}, wantRs: "bikkuri", wantErr: false},
		{name: "ぺちゃんこ", args: args{ks: "ぺちゃんこ"}, wantRs: "pechanko", wantErr: false},
		{name: "すっごい", args: args{ks: "すっごい"}, wantRs: "suggoi", wantErr: false},
		{name: "ほっそり", args: args{ks: "ほっそり"}, wantRs: "hossori", wantErr: false},
		{name: "ちょっぴり", args: args{ks: "ちょっぴり"}, wantRs: "choppiri", wantErr: false},
		{name: "ゆっくり", args: args{ks: "ゆっくり"}, wantRs: "yukkuri", wantErr: false},
		{name: "ちょうちょ", args: args{ks: "ちょうちょ"}, wantRs: "chocho", wantErr: false},
		{name: "ちゃんと", args: args{ks: "ちゃんと"}, wantRs: "chanto", wantErr: false},
		{name: "すーぱー", args: args{ks: "すーぱー"}, wantRs: "supa", wantErr: false},
		{name: "ひょうが", args: args{ks: "ひょうが"}, wantRs: "hyoga", wantErr: false},
		{name: "にっこり", args: args{ks: "にっこり"}, wantRs: "nikkori", wantErr: false},
		{name: "ぶっちゃけ", args: args{ks: "ぶっちゃけ"}, wantRs: "butchake", wantErr: false},
		{name: "ちゅうい", args: args{ks: "ちゅうい"}, wantRs: "chui", wantErr: false},
		{name: "ちょうだい", args: args{ks: "ちょうだい"}, wantRs: "chodai", wantErr: false},
		{name: "もっちり", args: args{ks: "もっちり"}, wantRs: "motchiri", wantErr: false},
		{name: "ちょくちょく", args: args{ks: "ちょくちょく"}, wantRs: "chokuchoku", wantErr: false},
		{name: "かんぱい", args: args{ks: "かんぱい"}, wantRs: "kampai", wantErr: false},
		{name: "ひびき", args: args{ks: "ひびき"}, wantRs: "hibiki", wantErr: false},
		{name: "さんぽ", args: args{ks: "さんぽ"}, wantRs: "sampo", wantErr: false},
		{name: "けんぽう", args: args{ks: "けんぽう"}, wantRs: "kempo", wantErr: false},
		{name: "しんぱい", args: args{ks: "しんぱい"}, wantRs: "shimpai", wantErr: false},
		{name: "せんべい", args: args{ks: "せんべい"}, wantRs: "sembei", wantErr: false},
		{name: "かんぱん", args: args{ks: "かんぱん"}, wantRs: "kampan", wantErr: false},
		{name: "こんぴら", args: args{ks: "こんぴら"}, wantRs: "kompira", wantErr: false},
		{name: "えんぴつ", args: args{ks: "えんぴつ"}, wantRs: "empitsu", wantErr: false},
		{name: "たんぼ", args: args{ks: "たんぼ"}, wantRs: "tambo", wantErr: false},
		{name: "きんもくせい", args: args{ks: "きんもくせい"}, wantRs: "kimmokusei", wantErr: false},
		{name: "ちゅうもく", args: args{ks: "ちゅうもく"}, wantRs: "chumoku", wantErr: false},
		{name: "かんむり", args: args{ks: "かんむり"}, wantRs: "kammuri", wantErr: false},
		{name: "かんもく", args: args{ks: "かんもく"}, wantRs: "kammoku", wantErr: false},
		{name: "あんまり", args: args{ks: "あんまり"}, wantRs: "ammari", wantErr: false},
		{name: "たかし", args: args{ks: "たかし"}, wantRs: "takashi", wantErr: false},
		{name: "はなこ", args: args{ks: "はなこ"}, wantRs: "hanako", wantErr: false},
		{name: "よしえ", args: args{ks: "よしえ"}, wantRs: "yoshie", wantErr: false},
		{name: "たける", args: args{ks: "たける"}, wantRs: "takeru", wantErr: false},
		{name: "さちこ", args: args{ks: "さちこ"}, wantRs: "sachiko", wantErr: false},
		{name: "まさと", args: args{ks: "まさと"}, wantRs: "masato", wantErr: false},
		{name: "なおみ", args: args{ks: "なおみ"}, wantRs: "naomi", wantErr: false},
		{name: "ともこ", args: args{ks: "ともこ"}, wantRs: "tomoko", wantErr: false},
		{name: "けんじ", args: args{ks: "けんじ"}, wantRs: "kenji", wantErr: false},
		{name: "みゆき", args: args{ks: "みゆき"}, wantRs: "miyuki", wantErr: false},
		{name: "たなか", args: args{ks: "たなか"}, wantRs: "tanaka", wantErr: false},
		{name: "すずき", args: args{ks: "すずき"}, wantRs: "suzuki", wantErr: false},
		{name: "さとう", args: args{ks: "さとう"}, wantRs: "sato", wantErr: false},
		{name: "いとう", args: args{ks: "いとう"}, wantRs: "ito", wantErr: false},
		{name: "やまもと", args: args{ks: "やまもと"}, wantRs: "yamamoto", wantErr: false},
		{name: "いしい", args: args{ks: "いしい"}, wantRs: "ishii", wantErr: false},
		{name: "ささき", args: args{ks: "ささき"}, wantRs: "sasaki", wantErr: false},
		{name: "こばやし", args: args{ks: "こばやし"}, wantRs: "kobayashi", wantErr: false},
		{name: "まつもと", args: args{ks: "まつもと"}, wantRs: "matsumoto", wantErr: false},
		{name: "なかむら", args: args{ks: "なかむら"}, wantRs: "nakamura", wantErr: false},
		{name: "くつろぐ", args: args{ks: "くつろぐ"}, wantRs: "kutsurogu", wantErr: false},
		{name: "ほそながい", args: args{ks: "ほそながい"}, wantRs: "hosonagai", wantErr: false},
		{name: "ぴょんぴょん", args: args{ks: "ぴょんぴょん"}, wantRs: "pyompyon", wantErr: false},
		{name: "なつかしい", args: args{ks: "なつかしい"}, wantRs: "natsukashii", wantErr: false},
		{name: "ごましお", args: args{ks: "ごましお"}, wantRs: "gomashio", wantErr: false},
		{name: "ゆるやか", args: args{ks: "ゆるやか"}, wantRs: "yuruyaka", wantErr: false},
		{name: "すみっこ", args: args{ks: "すみっこ"}, wantRs: "sumikko", wantErr: false},
		{name: "ぼさぼさ", args: args{ks: "ぼさぼさ"}, wantRs: "bosabosa", wantErr: false},
		{name: "きらめく", args: args{ks: "きらめく"}, wantRs: "kirameku", wantErr: false},
		{name: "ぐるぐる", args: args{ks: "ぐるぐる"}, wantRs: "guruguru", wantErr: false},
		{name: "めでたい", args: args{ks: "めでたい"}, wantRs: "medetai", wantErr: false},
		{name: "むちゅう", args: args{ks: "むちゅう"}, wantRs: "muchu", wantErr: false},
		{name: "ぶよぶよ", args: args{ks: "ぶよぶよ"}, wantRs: "buyobuyo", wantErr: false},
		{name: "さっぱり", args: args{ks: "さっぱり"}, wantRs: "sappari", wantErr: false},
		{name: "まぶしい", args: args{ks: "まぶしい"}, wantRs: "mabushii", wantErr: false},
		{name: "ぬくもり", args: args{ks: "ぬくもり"}, wantRs: "nukumori", wantErr: false},
		{name: "ふんわり", args: args{ks: "ふんわり"}, wantRs: "funwari", wantErr: false},
		{name: "ひんやり", args: args{ks: "ひんやり"}, wantRs: "hinyari", wantErr: false},
		{name: "むしむし", args: args{ks: "むしむし"}, wantRs: "mushimushi", wantErr: false},
		{name: "ちょっぴり", args: args{ks: "ちょっぴり"}, wantRs: "choppiri", wantErr: false},
		{name: "ぱりぱり", args: args{ks: "ぱりぱり"}, wantRs: "paripari", wantErr: false},
		{name: "わくわく", args: args{ks: "わくわく"}, wantRs: "wakuwaku", wantErr: false},
		{name: "びしょびしょ", args: args{ks: "びしょびしょ"}, wantRs: "bishobisho", wantErr: false},
		{name: "くるくる", args: args{ks: "くるくる"}, wantRs: "kurukuru", wantErr: false},
		{name: "むさくるしい", args: args{ks: "むさくるしい"}, wantRs: "musakurushii", wantErr: false},
		{name: "じっくり", args: args{ks: "じっくり"}, wantRs: "jikkuri", wantErr: false},
		{name: "ふらふら", args: args{ks: "ふらふら"}, wantRs: "furafura", wantErr: false},
		{name: "よろこぶ", args: args{ks: "よろこぶ"}, wantRs: "yorokobu", wantErr: false},
		{name: "すっきり", args: args{ks: "すっきり"}, wantRs: "sukkiri", wantErr: false},
		{name: "ぴかぴか", args: args{ks: "ぴかぴか"}, wantRs: "pikapika", wantErr: false},
		{name: "はきはき", args: args{ks: "はきはき"}, wantRs: "hakihaki", wantErr: false},
		{name: "もぐもぐ", args: args{ks: "もぐもぐ"}, wantRs: "mogumogu", wantErr: false},
		{name: "ぽかぽか", args: args{ks: "ぽかぽか"}, wantRs: "pokapoka", wantErr: false},
		{name: "ぴりぴり", args: args{ks: "ぴりぴり"}, wantRs: "piripiri", wantErr: false},
		{name: "ほっそり", args: args{ks: "ほっそり"}, wantRs: "hossori", wantErr: false},
		{name: "ぴんぴん", args: args{ks: "ぴんぴん"}, wantRs: "pimpin", wantErr: false},
		{name: "すやすや", args: args{ks: "すやすや"}, wantRs: "suyasuya", wantErr: false},
		{name: "さらさら", args: args{ks: "さらさら"}, wantRs: "sarasara", wantErr: false},
		{name: "ばたばた", args: args{ks: "ばたばた"}, wantRs: "batabata", wantErr: false},
		{name: "ゆるゆる", args: args{ks: "ゆるゆる"}, wantRs: "yuruyuru", wantErr: false},
		{name: "ふわふわ", args: args{ks: "ふわふわ"}, wantRs: "fuwafuwa", wantErr: false},
		{name: "ざっくり", args: args{ks: "ざっくり"}, wantRs: "zakkuri", wantErr: false},
		{name: "ぎゅっと", args: args{ks: "ぎゅっと"}, wantRs: "gyutto", wantErr: false},
		{name: "どんどん", args: args{ks: "どんどん"}, wantRs: "dondon", wantErr: false},
		{name: "ぴちぴち", args: args{ks: "ぴちぴち"}, wantRs: "pichipichi", wantErr: false},
		{name: "ゆらゆら", args: args{ks: "ゆらゆら"}, wantRs: "yurayura", wantErr: false},
		{name: "さっぱり", args: args{ks: "さっぱり"}, wantRs: "sappari", wantErr: false},
		{name: "ぐずぐず", args: args{ks: "ぐずぐず"}, wantRs: "guzuguzu", wantErr: false},
		{name: "ぺらぺら", args: args{ks: "ぺらぺら"}, wantRs: "perapera", wantErr: false},
		{name: "ゆきだるま", args: args{ks: "ゆきだるま"}, wantRs: "yukidaruma", wantErr: false},
		{name: "くるりん", args: args{ks: "くるりん"}, wantRs: "kururin", wantErr: false},
		{name: "めくるめく", args: args{ks: "めくるめく"}, wantRs: "mekurumeku", wantErr: false},
		{name: "ぬれぬれ", args: args{ks: "ぬれぬれ"}, wantRs: "nurenure", wantErr: false},
		{name: "ふんわり", args: args{ks: "ふんわり"}, wantRs: "funwari", wantErr: false},
		{name: "はらはら", args: args{ks: "はらはら"}, wantRs: "harahara", wantErr: false},
		{name: "むにゅむにゅ", args: args{ks: "むにゅむにゅ"}, wantRs: "munyumunyu", wantErr: false},
		{name: "ごろごろ", args: args{ks: "ごろごろ"}, wantRs: "gorogoro", wantErr: false},
		{name: "くるっと", args: args{ks: "くるっと"}, wantRs: "kurutto", wantErr: false},
		{name: "ぴかりと", args: args{ks: "ぴかりと"}, wantRs: "pikarito", wantErr: false},
		{name: "うきうき", args: args{ks: "うきうき"}, wantRs: "ukiuki", wantErr: false},
		{name: "ぶらぶら", args: args{ks: "ぶらぶら"}, wantRs: "burabura", wantErr: false},
		{name: "むしゃむしゃ", args: args{ks: "むしゃむしゃ"}, wantRs: "mushamusha", wantErr: false},
		{name: "ぽつんと", args: args{ks: "ぽつんと"}, wantRs: "potsunto", wantErr: false},
		{name: "ふらりと", args: args{ks: "ふらりと"}, wantRs: "furarito", wantErr: false},
		{name: "まるまる", args: args{ks: "まるまる"}, wantRs: "marumaru", wantErr: false},
		{name: "ゆらゆら", args: args{ks: "ゆらゆら"}, wantRs: "yurayura", wantErr: false},
		{name: "ぴかぴか", args: args{ks: "ぴかぴか"}, wantRs: "pikapika", wantErr: false},
		{name: "さらりと", args: args{ks: "さらりと"}, wantRs: "sararito", wantErr: false},
		{name: "ぼさぼさ", args: args{ks: "ぼさぼさ"}, wantRs: "bosabosa", wantErr: false},
		{name: "ぽかんと", args: args{ks: "ぽかんと"}, wantRs: "pokanto", wantErr: false},
		{name: "ごろんと", args: args{ks: "ごろんと"}, wantRs: "goronto", wantErr: false},
		{name: "ちょいちょい", args: args{ks: "ちょいちょい"}, wantRs: "choichoi", wantErr: false},
		{name: "ぐっすり", args: args{ks: "ぐっすり"}, wantRs: "gussuri", wantErr: false},
		{name: "よちよち", args: args{ks: "よちよち"}, wantRs: "yochiyochi", wantErr: false},
		{name: "にこにこ", args: args{ks: "にこにこ"}, wantRs: "nikoniko", wantErr: false},
		{name: "ほっと", args: args{ks: "ほっと"}, wantRs: "hotto", wantErr: false},
		{name: "ひやひや", args: args{ks: "ひやひや"}, wantRs: "hiyahiya", wantErr: false},
		{name: "ばたばた", args: args{ks: "ばたばた"}, wantRs: "batabata", wantErr: false},
		{name: "ぐんぐん", args: args{ks: "ぐんぐん"}, wantRs: "gungun", wantErr: false},
		{name: "めんどう", args: args{ks: "めんどう"}, wantRs: "mendo", wantErr: false},
		{name: "ちりちり", args: args{ks: "ちりちり"}, wantRs: "chirichiri", wantErr: false},
		{name: "うとうと", args: args{ks: "うとうと"}, wantRs: "utoto", wantErr: false},
		{name: "さくさく", args: args{ks: "さくさく"}, wantRs: "sakusaku", wantErr: false},
		{name: "もそもそ", args: args{ks: "もそもそ"}, wantRs: "mosomoso", wantErr: false},
		{name: "ぐずぐず", args: args{ks: "ぐずぐず"}, wantRs: "guzuguzu", wantErr: false},
		{name: "よくばり", args: args{ks: "よくばり"}, wantRs: "yokubari", wantErr: false},
		{name: "ずるずる", args: args{ks: "ずるずる"}, wantRs: "zuruzuru", wantErr: false},
		{name: "ぐいぐい", args: args{ks: "ぐいぐい"}, wantRs: "guigui", wantErr: false},
		{name: "ぺこぺこ", args: args{ks: "ぺこぺこ"}, wantRs: "pekopeko", wantErr: false},
		{name: "さらさら", args: args{ks: "さらさら"}, wantRs: "sarasara", wantErr: false},
		{name: "むしむし", args: args{ks: "むしむし"}, wantRs: "mushimushi", wantErr: false},
		{name: "ほっぺた", args: args{ks: "ほっぺた"}, wantRs: "hoppeta", wantErr: false},
		{name: "まっすぐ", args: args{ks: "まっすぐ"}, wantRs: "massugu", wantErr: false},
		{name: "むちゅう", args: args{ks: "むちゅう"}, wantRs: "muchu", wantErr: false},
		{name: "ひょうひょう", args: args{ks: "ひょうひょう"}, wantRs: "hyohyo", wantErr: false},
		{name: "ふんわり", args: args{ks: "ふんわり"}, wantRs: "funwari", wantErr: false},
		{name: "ひんやり", args: args{ks: "ひんやり"}, wantRs: "hinyari", wantErr: false},
		{name: "ふらふら", args: args{ks: "ふらふら"}, wantRs: "furafura", wantErr: false},
		{name: "ざっくり", args: args{ks: "ざっくり"}, wantRs: "zakkuri", wantErr: false},
		{name: "ぴりぴり", args: args{ks: "ぴりぴり"}, wantRs: "piripiri", wantErr: false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gotRs, err := convertKanaToRomaji(tt.args.ks)
			if (err != nil) != tt.wantErr {
				t.Errorf("convertKanaToRomaji() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if gotRs != tt.wantRs {
				t.Errorf("convertKanaToRomaji() = %v, want %v", gotRs, tt.wantRs)
			}
		})
	}
}
